Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/ArgumentAlignment:
  Exclude:
    - 'config/initializers/cors.rb'

Layout/CommentIndentation:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

Layout/EmptyLines:
  Exclude:
    - 'config/environments/development.rb'
    - 'db/migrate/20250205214954_devise_create_users.rb'

Layout/EmptyLinesAroundAccessModifier:
  Exclude:
    - 'app/controllers/application_controller.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'config/initializers/cors.rb'

ayout/EmptyLinesAroundClassBody:
  Exclude:

Layout/EmptyLinesAroundMethodBody:
  Exclude:

Layout/EndAlignment:
  Exclude:

Layout/HashAlignment:
  Exclude:
    - 'config/routes.rb'

Layout/IndentationWidth:
  Exclude:

Layout/LeadingCommentSpace:
  Exclude:
    # - 'app/controllers/users/registrations_controller.rb'

Layout/MultilineHashBraceLayout:
  Exclude:
    # - 'app/controllers/users/registrations_controller.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    # - 'app/controllers/api/v1/tasks_controller.rb'

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    # - 'Gemfile'
    # - 'app/controllers/application_controller.rb'

Layout/TrailingEmptyLines:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'config/application.rb'

Layout/TrailingWhitespace:
  Exclude:

Metrics/AbcSize:
  Max: 19

Metrics/BlockLength:
  Max: 26


Metrics/CyclomaticComplexity:
  Max: 9


Metrics/MethodLength:
  Max: 16


Metrics/PerceivedComplexity:
  Max: 9


Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/api/v1/tasks_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/api/v1/tasks_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'app/models/task.rb'
    - 'app/models/user.rb'
    - 'app/serializers/user_serializer.rb'
    - 'config/application.rb'
    - 'db/migrate/20250205214954_devise_create_users.rb'
    - 'db/migrate/20250205221217_add_name_to_users.rb'
    - 'db/migrate/20250205221622_add_jti_to_users.rb'
    - 'db/migrate/20250206203150_create_tasks.rb'
    - 'db/migrate/20250213203156_add_role_to_users.rb'


Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/HashSyntax:
  Exclude:
    - 'Gemfile'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/application.rb'

Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Layout/LineLength:
  Max: 100
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/20250205214954_devise_create_users.rb'

Style/SpecialGlobalVars:
  Enabled: false

Lint/EmptyFile:
  Enabled: false
