default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: task_management_user
  password: 123456
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_manager_backend_development

test:
  <<: *default
  database: task_manager_backend_test

production:
  <<: *default
  database: task_manager_backend_production
  username: task_manager_backend
  password: <%= ENV["TASK_MANAGER_BACKEND_DATABASE_PASSWORD"] %>